// Generated by LiveScript 1.2.0
var main;
main = function($scope, $http){
  var uid, accessToken, getAccessToken, getWall;
  uid = "";
  accessToken = "";
  $scope.wall = [];
  FB.init({
    appId: "1490131354539691",
    status: true,
    cookie: true,
    xfbml: true,
    oauth: true
  });
  getAccessToken = function(){
    console.log("get login status...");
    return FB.getLoginStatus(function(res){
      var ref$;
      console.log("response...");
      if (res.status === "connected") {
        ref$ = {
          userID: (ref$ = res.authResponse).userID,
          accessToken: ref$.accessToken
        }, uid = ref$.uid, accessToken = ref$.accessToken;
        return console.log(accessToken);
      } else {
        return console.log("please login");
      }
    });
  };
  getWall = function(url){
    return $http.get(url).success(function(data){
      console.log(data);
      console.log(data.paging.next);
      $scope.wall = $scope.wall.concat(data.data);
      if (data.paging && data.paging.next) {
        return setTimeout(function(){
          return getWall(data.paging.next);
        }, 100);
      }
    });
  };
  $('#FBLogin').click(function(){
    return FB.login(function(){
      return getAccessToken();
    }, {
      scope: ""
    });
  });
  getAccessToken();
  return $('#show').click(function(){
    return getWall("https://graph.facebook.com/NtuNewsEForum/feed?access_token=" + accessToken);
  });
};